server:
  port: 8877
spring:
  application:
    name: customServices
mybatis:
  type-aliases-package: com.hp.pojo
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:1007/eureka
    registry-fetch-interval-seconds: 5   #5秒间隔获取服务列表
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
    instance-id: ${spring.application.name}:${server.port}
    #            设置超时
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
ribbon:
  ConnectionTimeOut: 500 #建立连接时间
  ReadTimeOut: 2000 #feign中ribbon配置
feign:
  hystrix:
    enabled: true # 开启Feign的熔断功能