server:
  port: 1007
spring:
  application:
    name: ecukaService
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1001/eureka
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 1000
